"""EXP-004: train, select, and test the revised satellite-level MAPPO."""

from __future__ import annotations

import argparse
import csv
from dataclasses import asdict
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import time
from typing import Dict, Iterable

import numpy as np

from hierarchical_statistics import (
    DEFAULT_BOOTSTRAP_RESAMPLES,
    add_multiplicity_corrections,
    build_crossed_matrix,
    crossed_mean_summary,
    pair_crossed_matrices,
    paired_crossed_summary,
    statistical_analysis_manifest,
)
from mappo_evaluation import (
    EpisodeMetrics,
    GlobalDijkstraPolicy,
    OspfEcmpPolicy,
    evaluate_policy,
    heuristic_policy,
    load_checkpoint_policy,
    train_q_routing,
)
from variant_definitions import (
    CANONICAL_VARIANTS,
    LEGACY_VARIANT_ALIASES,
    canonical_variant_name,
    resolve_variant,
)


ALL_SCENARIOS = [
    "low_load",
    "medium_load",
    "hotspot_high_load",
    "frequent_break",
    "fault_links",
]
# Frozen before the new confirmatory 50k matrix. These seeds were generated by
# the SHA-256 rule documented in ABLATION_50K_PROTOCOL.md and do not occur in
# any historical result artifact inspected during method development.
POLICY_SEEDS = [
    2009387241,
    688652842,
    1824192069,
    1446495455,
    140273932,
    1016147766,
    885581732,
    247192783,
    1367579272,
    1996870291,
    646895287,
    489261598,
]
METRICS = [
    "delivery_ratio",
    "drop_rate",
    "throughput_packets_per_slot",
    "average_delay_slots",
    "p95_delay_slots",
    "mean_queue_packets",
    "routing_switches",
    "episode_reward",
    "global_delay_cost",
    "global_queue_cost",
    "global_load_imbalance",
    "global_switch_cost",
    "global_throughput_reward",
    "global_control_overhead_ratio",
    "global_drop_cost",
]


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--mode",
        choices=["quick", "x2k", "x10k", "full"],
        default="quick",
    )
    parser.add_argument("--output", type=Path, default=Path("experiments/archive/EXP-004"))
    parser.add_argument("--cleanmarl", type=Path, default=Path("F:/cleanmarl"))
    parser.add_argument("--project", type=Path, default=Path(__file__).resolve().parent)
    parser.add_argument("--skip-training", action="store_true")
    parser.add_argument("--device", default="cpu")
    parser.add_argument(
        "--variant",
        choices=sorted(set(CANONICAL_VARIANTS) | set(LEGACY_VARIANT_ALIASES)),
        default="proposed",
        help=(
            "Canonical LEO method variant. proposed is the frozen L0 headline "
            "method; full/no_lifetime remain legacy aliases only."
        ),
    )
    return parser.parse_args()


def mode_config(mode: str) -> Dict:
    if mode == "full":
        return {
            "scenarios": ALL_SCENARIOS,
            "timesteps": 50000,
            "validation_episodes": 50,
            "test_episodes": 50,
            "eval_every_rollouts": 40,
            "save_every_steps": 5000,
            "batch_size": 4,
            "q_routing_train_episodes": 500,
        }
    if mode == "x10k":
        # Budget-sensitivity preset: 10k steps, all scenarios. Sits between
        # quick and full; used for the delivery-vs-steps crossover figure.
        return {
            "scenarios": ALL_SCENARIOS,
            "timesteps": 10000,
            "validation_episodes": 50,
            "test_episodes": 50,
            "eval_every_rollouts": 20,
            "save_every_steps": 2500,
            "batch_size": 4,
            "q_routing_train_episodes": 400,
        }
    if mode == "x2k":
        # Budget-sensitivity preset: 2k steps, all scenarios.
        return {
            "scenarios": ALL_SCENARIOS,
            "timesteps": 2000,
            "validation_episodes": 30,
            "test_episodes": 30,
            "eval_every_rollouts": 5,
            "save_every_steps": 500,
            "batch_size": 4,
            "q_routing_train_episodes": 200,
        }
    return {
        "scenarios": ["medium_load", "frequent_break"],
        "timesteps": 300,
        "validation_episodes": 20,
        "test_episodes": 20,
        "eval_every_rollouts": 2,
        "save_every_steps": 150,
        "batch_size": 2,
        "q_routing_train_episodes": 100,
    }


def find_selected_checkpoint(run_root: Path) -> Path | None:
    manifests = sorted(
        run_root.glob("*/run_manifest.json"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    for manifest_path in manifests:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        selected = manifest.get("validation_best_checkpoint")
        if selected:
            selected_path = Path(selected)
            if not selected_path.is_absolute():
                selected_path = manifest_path.parent / selected_path.name
            if selected_path.exists():
                return selected_path
    return None


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def code_fingerprint(args) -> Dict[str, str]:
    paths = {
        "training_entry": Path(__file__).resolve(),
        "trainer": args.cleanmarl / "cleanmarl" / "mappo.py",
        "trainer_snapshot": args.project / "cleanmarl_mappo_leo.py",
        "external_design": args.cleanmarl / "cleanmarl" / "mappo_design.py",
        "base_environment": args.project / "leo_marl_env.py",
        "environment": args.project / "leo_multiagent_env.py",
        "wrapper": args.project / "cleanmarl_leo_multiagent_wrapper.py",
        "design": args.project / "mappo_design.py",
        "evaluation": args.project / "mappo_evaluation.py",
        "variant_definitions": args.project / "variant_definitions.py",
    }
    fingerprints = {name: sha256(path.resolve()) for name, path in paths.items()}
    if fingerprints["trainer"] != fingerprints["trainer_snapshot"]:
        raise RuntimeError(
            "external CleanMARL trainer does not match the frozen repository "
            "snapshot; synchronize cleanmarl/mappo.py before training"
        )
    if fingerprints["external_design"] != fingerprints["design"]:
        raise RuntimeError(
            "external CleanMARL design module does not match the frozen repository "
            "snapshot; synchronize cleanmarl/mappo_design.py before training"
        )
    return fingerprints


def train_one(
    args,
    config: Dict,
    scenario: str,
    policy_seed: int,
    variant: str = "proposed",
    trainer_overrides: list[str] | None = None,
) -> Path:
    environment_variant = canonical_variant_name(variant)
    run_root = (
        args.output.resolve()
        / "checkpoints"
        / scenario
        / variant
        / f"seed_{policy_seed}"
    )
    run_root.mkdir(parents=True, exist_ok=True)
    fingerprint = {
        "code": code_fingerprint(args),
        "scenario": scenario,
        "policy_seed": policy_seed,
        "experiment_variant": variant,
        "environment_variant": environment_variant,
        "variant_definition": resolve_variant(variant).as_dict(),
        "config": config,
        "trainer_overrides": trainer_overrides or [],
    }
    fingerprint_path = run_root / "code_fingerprint.json"
    existing = find_selected_checkpoint(run_root)
    fingerprint_matches = (
        fingerprint_path.exists()
        and json.loads(fingerprint_path.read_text(encoding="utf-8")) == fingerprint
    )
    if args.skip_training:
        if existing is None or not fingerprint_matches:
            raise FileNotFoundError(f"no selected checkpoint under {run_root}")
        return existing
    if existing is not None and fingerprint_matches:
        return existing

    command = [
        sys.executable,
        str(args.cleanmarl / "cleanmarl" / "mappo.py"),
        "--env-type", "leo_multi",
        "--env-name", scenario,
        "--leo-project-path", str(args.project),
        "--leo-variant", environment_variant,
        "--seed", str(policy_seed),
        "--batch-size", str(config["batch_size"]),
        "--total-timesteps", str(config["timesteps"]),
        "--epochs", "3",
        "--num-minibatches", "4",
        "--eval-steps", str(config["eval_every_rollouts"]),
        "--num-eval-ep", str(config["validation_episodes"]),
        "--save-every-steps", str(config["save_every_steps"]),
        "--checkpoint-dir", str(run_root),
        "--run-tag", "EXP-004",
        "--train-seed-start", "9001",
        "--train-seed-count", "200",
        "--validation-seed-start", "10001",
        "--device", args.device,
    ]
    command.extend(trainer_overrides or [])
    stdout_path = run_root / "trainer_stdout.log"
    started_at = time.monotonic()
    with stdout_path.open("w", encoding="utf-8", newline="") as stdout:
        process = subprocess.Popen(
            command,
            cwd=args.cleanmarl,
            text=True,
            encoding="utf-8",
            errors="replace",
            stdout=stdout,
            stderr=subprocess.STDOUT,
        )
        print(
            f"started training {scenario}/seed={policy_seed} pid={process.pid}",
            flush=True,
        )
        try:
            while True:
                try:
                    return_code = process.wait(timeout=30.0)
                    break
                except subprocess.TimeoutExpired:
                    stdout.flush()
                    elapsed_minutes = (time.monotonic() - started_at) / 60.0
                    print(
                        f"training heartbeat {scenario}/seed={policy_seed} "
                        f"pid={process.pid} elapsed={elapsed_minutes:.1f} min",
                        flush=True,
                    )
        except BaseException:
            process.terminate()
            try:
                process.wait(timeout=10.0)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()
            raise
    if return_code != 0:
        raise RuntimeError(
            f"training failed for {scenario}/seed={policy_seed}; "
            f"see {stdout_path}"
        )
    selected = find_selected_checkpoint(run_root)
    if selected is None:
        raise RuntimeError(f"training produced no validation-best checkpoint: {run_root}")
    fingerprint_path.write_text(
        json.dumps(fingerprint, indent=2), encoding="utf-8"
    )
    return selected


def write_csv(path: Path, rows: Iterable[Dict]) -> None:
    rows = list(rows)
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def aggregate_rows(rows: list[EpisodeMetrics]) -> list[Dict]:
    result = []
    keys = sorted({(row.scenario, row.policy) for row in rows})
    for group_index, (scenario, policy) in enumerate(keys):
        selected = [row for row in rows if row.scenario == scenario and row.policy == policy]
        for metric_index, metric in enumerate(METRICS):
            matrix = build_crossed_matrix(selected, metric)
            summary = crossed_mean_summary(
                matrix,
                rng_seed=4000 + 100 * group_index + metric_index,
                resamples=DEFAULT_BOOTSTRAP_RESAMPLES,
            )
            result.append(
                {
                    "scenario": scenario,
                    "policy": policy,
                    "metric": metric,
                    **summary,
                }
            )
    return result


def paired_tests(rows: list[EpisodeMetrics]) -> list[Dict]:
    results = []
    baselines = [
            "delay_only",
            "full_heuristic",
            "global_dijkstra",
            "ospf_ecmp",
            "q_routing",
    ]
    for scenario_index, scenario in enumerate(
        sorted({row.scenario for row in rows})
    ):
        for baseline_index, baseline in enumerate(baselines):
            for metric in METRICS:
                learned = [
                    row
                    for row in rows
                    if row.scenario == scenario and row.policy == "mappo"
                ]
                reference = [
                    row
                    for row in rows
                    if row.scenario == scenario and row.policy == baseline
                ]
                paired = pair_crossed_matrices(learned, reference, metric)
                metric_index = METRICS.index(metric)
                summary = paired_crossed_summary(
                    paired,
                    rng_seed=(
                        8000
                        + 1000 * scenario_index
                        + 100 * baseline_index
                        + metric_index
                    ),
                    resamples=DEFAULT_BOOTSTRAP_RESAMPLES,
                )
                results.append(
                    {
                        "scenario": scenario,
                        "baseline": baseline,
                        "metric": metric,
                        "paired_policy_seeds": summary["policy_seed_count"],
                        "paired_workloads": summary["workload_seed_count"],
                        "paired_episode_cells": summary["episode_pair_count"],
                        "policy_seed_pairing": summary["policy_seed_pairing"],
                        "mappo_mean": summary["treatment_mean"],
                        "baseline_mean": summary["reference_mean"],
                        "mean_difference": summary["mean_difference"],
                        "median_difference": summary[
                            "median_policy_seed_mean_difference"
                        ],
                        "policy_seed_mean_difference_std": summary[
                            "policy_seed_mean_difference_std"
                        ],
                        "difference_ci95_low": summary["difference_ci95_low"],
                        "difference_ci95_high": summary["difference_ci95_high"],
                        "bootstrap_standard_error": summary[
                            "bootstrap_standard_error"
                        ],
                        "difference_ci_method": summary["difference_ci_method"],
                        "ci_resamples": summary["ci_resamples"],
                        "paired_cohen_dz": summary["paired_cohen_dz"],
                        "paired_hedges_gz": summary["paired_hedges_gz"],
                        "rank_biserial_correlation": summary[
                            "rank_biserial_correlation"
                        ],
                        "positive_policy_seed_fraction": summary[
                            "positive_policy_seed_fraction"
                        ],
                        "sign_flip_statistic": summary["sign_flip_statistic"],
                        "sign_flip_permutations": summary[
                            "sign_flip_permutations"
                        ],
                        "raw_p_value": summary["raw_p_value"],
                        "p_value_method": summary["p_value_method"],
                        "seed_level_wilcoxon_statistic": summary[
                            "seed_level_wilcoxon_statistic"
                        ],
                        "seed_level_wilcoxon_p": summary[
                            "seed_level_wilcoxon_p"
                        ],
                        "seed_level_wilcoxon_method": summary[
                            "seed_level_wilcoxon_method"
                        ],
                    }
                )
    add_multiplicity_corrections(
        results,
        family_keys=("metric",),
        holm_key="confirmatory_holm_within_metric_p",
        benjamini_hochberg_key="within_metric_bh_sensitivity_p",
        family_size_key="within_metric_family_size",
    )
    add_multiplicity_corrections(
        results,
        holm_key="global_holm_sensitivity_p",
        benjamini_hochberg_key="global_bh_exploratory_p",
        family_size_key="global_family_size",
    )
    for row in results:
        row["multiplicity_role"] = (
            "primary_confirmatory_family"
            if row["metric"] == "delivery_ratio"
            else "secondary_metric_family"
        )
        # Retain the historical column consumed by make_figures.py.  Its scope
        # is now explicit in the adjacent global_bh_exploratory_p column.
        row["benjamini_hochberg_p"] = row["global_bh_exploratory_p"]
    return results


def main():
    args = parse_args()
    config = mode_config(args.mode)
    args.output.mkdir(parents=True, exist_ok=True)
    workload_seeds = range(11001, 11001 + config["test_episodes"])
    all_rows: list[EpisodeMetrics] = []
    checkpoints = {}
    environment_variant = canonical_variant_name(args.variant)

    for scenario in config["scenarios"]:
        for policy_seed in POLICY_SEEDS:
            checkpoint = train_one(args, config, scenario, policy_seed, variant=args.variant)
            checkpoints[f"{scenario}/seed_{policy_seed}"] = str(checkpoint)
            policy, _ = load_checkpoint_policy(checkpoint, device=args.device)
            all_rows.extend(
                evaluate_policy(
                    scenario,
                    "mappo",
                    policy,
                    policy_seed,
                    workload_seeds,
                    variant=environment_variant,
                )
            )
        for baseline in ["delay_only", "full_heuristic", "random"]:
            all_rows.extend(
                evaluate_policy(
                    scenario,
                    baseline,
                    heuristic_policy(baseline, seed=1234),
                    -1,
                    workload_seeds,
                    variant=environment_variant,
                )
            )
        all_rows.extend(
            evaluate_policy(
                scenario,
                "global_dijkstra",
                GlobalDijkstraPolicy(),
                -1,
                workload_seeds,
                variant=environment_variant,
            )
        )
        # OSPF/ECMP: the realistic distributed incumbent (shortest-path + ECMP
        # load split). Same information set as Dijkstra; required baseline for
        # isolating "learning" gain from "having a sensible SPF policy".
        all_rows.extend(
            evaluate_policy(
                scenario,
                "ospf_ecmp",
                OspfEcmpPolicy(seed=1234),
                -1,
                workload_seeds,
                variant=environment_variant,
            )
        )
        q_model_dir = args.output / "q_routing_models"
        q_model_dir.mkdir(parents=True, exist_ok=True)
        for policy_seed in POLICY_SEEDS:
            q_policy = train_q_routing(
                scenario,
                seed=policy_seed,
                episodes=config["q_routing_train_episodes"],
                variant=environment_variant,
            )
            np.savez_compressed(
                q_model_dir / f"{scenario}_seed_{policy_seed}.npz",
                q=q_policy.q,
            )
            all_rows.extend(
                evaluate_policy(
                    scenario,
                    "q_routing",
                    q_policy,
                    policy_seed,
                    workload_seeds,
                    variant=environment_variant,
                )
            )

    episode_dicts = [asdict(row) for row in all_rows]
    write_csv(args.output / "episode_metrics.csv", episode_dicts)
    write_csv(args.output / "aggregate_metrics.csv", aggregate_rows(all_rows))
    write_csv(args.output / "paired_tests.csv", paired_tests(all_rows))
    (args.output / "experiment_manifest.json").write_text(
        json.dumps(
            {
                "experiment": "EXP-004",
                "mode": args.mode,
                "config": config,
                "experiment_variant": args.variant,
                "environment_variant": environment_variant,
                "variant_definition": resolve_variant(args.variant).as_dict(),
                "policy_seeds": POLICY_SEEDS,
                "train_workload_seeds": [9001, 9200],
                "validation_workload_seeds": [
                    10001,
                    10000 + config["validation_episodes"],
                ],
                "test_workload_seeds": [
                    11001,
                    11000 + config["test_episodes"],
                ],
                "checkpoints": checkpoints,
                "code_fingerprint": code_fingerprint(args),
                "statistical_analysis": statistical_analysis_manifest(),
            },
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    print(f"EXP-004 complete: {args.output.resolve()}")


if __name__ == "__main__":
    main()
